version: 2

sources:
  - name: hospital_bronze
    database: project-5fbc8bf7-2dd6-4f0a-a5f
    schema: hospital_bronze

    tables:
      - name: departments
      - name: doctors

      - name: registrations
        config:
          loaded_at_field: updated_at
          freshness:
            warn_after:
              count: 30
              period: minute
            error_after:
              count: 60
              period: minute

      - name: encounters
      - name: admissions
      - name: discharges
      - name: billing